apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: monorepo-app
  namespace: mae
  labels:
    app.kubernetes.io/part-of: monorepo-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: monorepo-app
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
spec:
  params:
  - name: gitops_ssh_secret
    value: git-ssh
  source:
    git:
      url: ssh://git@github.com/Mpluya/config-steeltoe.git
      ref:
        branch: main
    subPath: config/mae/monorepo-app

