apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: customer-profile-justin
  namespace: justin
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: customer-profile-justin
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
spec:
  params:
  - name: gitops_ssh_secret
    value: git-ssh
  source:
    git:
      url: ssh://git@github.com/Mpluya/config-steeltoe.git
      ref:
        branch: main
    subPath: config/justin/customer-profile-justin

